### ISSUE TITLE
darkmode support

### ISSUE THREAD

**Issue by Mister-Hope** [academicpages/academicpages.github.io#1953] opened 2024-02-29 10:55 UTC
It would be great if the project could support darkmode.

**Comment by rjzupkoii** [comment] 2024-02-29 13:12
Dark mode support is planned, but it's going to be awhile before it's added since it's a fair amount of work to redo the styles. Closing as a duplicate of issue #911.

**Closed by rjzupkoii** 2024-02-29 13:12 UTC

**Comment by big-ccbtw** [comment] 2024-05-07 11:01
@rjzupkoii It'll be really amazing if the dark mode switch button could be implemented.
