### ISSUE TITLE
Build failing as of this week

### ISSUE THREAD

**Issue by ShayJordan** [academicpages/academicpages.github.io#1902] opened 2024-02-14 11:47 UTC
I've been using academicpages through GitHub Pages for around half a year now with no issues. Last successful build and deployment was Feb 1st, but tried to make a minor change to site content yesterday and the build is failing. It seems to be a problem unrelated to the changes I'm making as it's failing when I make a minor change to another site I'm running based on academicpages too. Has anyone had a similar experience or does anyone know what the issue or fix is here? Build log is below. Thanks!

`Run actions/jekyll-build-pages@v1
  with:
    source: .
    destination: ./_site
    future: false
    build_revision: 4a8f9[2](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:2)e5[3](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:3)1[4](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:4)0478d04ad288731a9cd222d0[5](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:5)feff
    verbose: true
    token: ***
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv1011_30b5d0 --label 9c591e --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/shay.github.io/shay.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.11
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Warning: The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/excerpt.rb:91: warning: Jekyll::Excerpt#yaml_file? at /usr/local/lib/ruby/2.7.0/forwardable.rb:154 forwarding to private method Jekyll::Page#yaml_file?
  Liquid Exception: undefined method `yaml_file?' for #<Jekyll::Page @name="about.md"> in /_layouts/single.html
/usr/local/lib/ruby/2.7.0/forwardable.rb:233:in `yaml_file?': undefined method `yaml_file?' for #<Jekyll::Page @name="about.md"> (NoMethodError)
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/excerpt.rb:91:in `render_with_liquid?'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:77:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:[6](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:6)2:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/excerpt.rb:83:in `output'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/excerpt.rb:[7](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:7)0:in `to_s'
	from /usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `to_s'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/filters.rb:19:in `markdownify'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/strainer.rb:56:in `invoke'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:[8](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:8)6:in `invoke'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:84:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `each'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `inject'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/variable.rb:82:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:80:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
	from /usr/local/bundle/gems/jekyll-3.[9](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:10).5/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/tags/include.rb:140:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/tags/include.rb:137:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:[10](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:11)3:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:126:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:195:in `render_layout'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:88:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:472:in `block in render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:471:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:471:in `render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:192:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-230/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-230/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v230 GitHub Pages: jekyll v3.9.5 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-paginate Requiring: jekyll-sitemap Requiring: jekyll-gist Requiring: jekyll-feed Requiring: jekyll-redirect-from Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-github-metadata Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /README.md EntryFilter: excluded /CHANGELOG.md EntryFilter: excluded /package.json EntryFilter: excluded /Gemfile EntryFilter: excluded /LICENSE Reading: _posts/2016-06-27-magic-moments.md Reading: _posts/2023-10-20-zone-of-proximal-development.md Reading: _posts/2020-02-29-your-next-chapter-in-ksw.md Reading: _posts/2020-05-26-allegory-of-martial-arts.md Reading: _posts/2023-10-08-why-kuk-sool.md Reading: _posts/2023-08-23-you-won-hwa.md Reading: _posts/2019-09-25-grading-nerves.md Reading: _posts/2016-03-27-jkn-to-ksn.md Reading: _posts/2023-09-[11](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:12)-nahk-bup.md Reading: _posts/2024-01-05-nineteen-years-of-kuk-sool-in-pictures.md EntryFilter: excluded /assets/js/vendor EntryFilter: excluded /assets/js/plugins Reading: _publications/2023-04-23-reflective-project-in-education.md Reading: _publications/2021-04-15-popular-mathematics.md Reading: _publications/2021-07-23-number-puzzles.md Reading: _publications/2022-05-[12](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:13)-goodsteins-theorem.md Reading: _portfolio/2019-05-28-mathsoc.md Reading: _portfolio/2016-05-29-waveney-eco.md Reading: _talks/2021-05-05-popular-mathematics.md Reading: _talks/2022-05-26-goodsteins-theorem.md Reading: _talks/2021-03-03-making-a-cup-of-sudoku.md Generating: JekyllRedirectFrom::Generator finished in 0.026006291 seconds. Generating: JekyllOptionalFrontMatter::Generator finished in 0.000211187 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.000111009 seconds. Generating: Jekyll::Paginate::Pagination finished in 5.74e-06 seconds. Generating: Jekyll::JekyllSitemap finished in 0.000695476 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000732335 seconds. Generating: JekyllRelativeLinks::Generator finished in 0.00[13](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:14)03318 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.000[14](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:15)64[15](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:16) seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 3.3443e-05 seconds. Rendering: _posts/20[16](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:17)-03-27-jkn-to-ksn.md Pre-Render Hooks: _posts/2016-03-27-jkn-to-ksn.md Rendering Markup: _posts/2016-03-27-jkn-to-ksn.md Requiring: kramdown-parser-gfm Rendering Layout: _posts/2016-03-27-jkn-to-ksn.md Layout source: site GitHub Metadata: Generating for ShayJordan/shay.github.io GitHub Metadata: Calling @client.pages("ShayJordan/shay.github.io", {}) Rendering: _posts/2016-06-27-magic-moments.md Pre-Render Hooks: _posts/2016-06-27-magic-moments.md Rendering Markup: _posts/2016-06-27-magic-moments.md Rendering Layout: _posts/2016-06-27-magic-moments.md Layout source: site Rendering: _posts/20[19](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:20)-09-25-grading-nerves.md Pre-Render Hooks: _posts/[20](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:21)19-09-[25](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:26)-grading-nerves.md Rendering Markup: _posts/2019-09-25-grading-nerves.md Rendering Layout: _posts/2019-09-25-grading-nerves.md Layout source: site Rendering: _posts/2020-02-29-your-next-chapter-in-ksw.md Pre-Render Hooks: _posts/2020-02-29-your-next-chapter-in-ksw.md Rendering Markup: _posts/2020-02-29-your-next-chapter-in-ksw.md Rendering Layout: _posts/2020-02-29-your-next-chapter-in-ksw.md Layout source: site Rendering: _posts/2020-05-[26](https://github.com/ShayJordan/shay.github.io/actions/runs/7900638094/job/21562565831#step:4:27)-allegory-of-martial-arts.md Pre-Render Hooks: _posts/2020-05-26-allegory-of-martial-arts.md Rendering Markup: _posts/2020-05-26-allegory-of-martial-arts.md Rendering Layout: _posts/202`

**Comment by linyongver** [comment] 2024-02-14 11:54
I have the same error

**Comment by gerardjoreilly** [comment] 2024-02-14 12:19
Yes, I have the same error as well

**Comment by mmdt01** [comment] 2024-02-14 12:56
I am facing the same problem too. 
Started building my page on Saturday (10/02/2024) which was working fine, but now I get build failure errors which are really confusing me :'(
Would appreciate any info if people find what the issue is!

**Comment by rjzupkoii** [comment] 2024-02-14 13:08
There error appears to be due to the `excerpt` being undefined YAML in Markdown in pages under the `_pages/*.md` path. I was able to fix my build by removing the lines in the relevant pages (see [example commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce)).

**Comment by alirk** [comment] 2024-02-14 13:10
I am facing the same issue

**Comment by ShayJordan** [comment] 2024-02-14 13:12
> There error appears to be due to the `excerpt` being undefined YAML in Markdown in pages under the `_pages/*.md` path. I was able to fix my build by removing the lines in the relevant pages (see [example commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce)).

That's interesting. I wonder what's causing that and if there's a proper fix rather than just deleting the excerpt from all pages and posts... I'm reluctant to do that as the excerpts are important to how things are presented in my archive pages.

**Comment by rjzupkoii** [comment] 2024-02-14 13:19
> > There error appears to be due to the `excerpt` being undefined YAML in Markdown in pages under the `_pages/*.md` path. I was able to fix my build by removing the lines in the relevant pages (see [example commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce)).
> 
> That's interesting. I wonder what's causing that and if there's a proper fix rather than just deleting the excerpt from all pages and posts... I'm reluctant to do that as the excerpts are important to how things are presented in my archive pages.

I'm not sure, I'd have to dig a bit more into the code base, which I didn't really have time for when working on getting my website updated. However, since the project is using a lot of older versions of various gems it might be due to something else that broke. I've reached out to @staeiou via email about the issue and will try to prepare a proper patch that I can open a pull request for in the next couple days.

**Comment by alirk** [comment] 2024-02-14 13:24
> > > There error appears to be due to the `excerpt` being undefined YAML in Markdown in pages under the `_pages/*.md` path. I was able to fix my build by removing the lines in the relevant pages (see [example commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce)).
> > 
> > 
> > That's interesting. I wonder what's causing that and if there's a proper fix rather than just deleting the excerpt from all pages and posts... I'm reluctant to do that as the excerpts are important to how things are presented in my archive pages.
> 
> I'm not sure, I'd have to dig a bit more into the code base, which I didn't really have time for when working on getting my website updated. However, since the project is using a lot of older versions of various gems it might be due to something else that broke. I've reached out to @staeiou via email about the issue and will try to prepare a proper patch that I can open a pull request for in the next couple days.

It will be great if this is fixed in a few days. I tried to remove 'excerpt_separator' in _config.yml but that did not work. Then following the message above, I searched 'excerpt' in the entire repo it is used everywhere for example: 

_includes/archive-single-cv.html:    {% if post.venue%}<p class="archive__item-excerpt" itemprop="description">{{ post.citation }}</p> {% endif %}
_includes/archive-single-talk-cv.html:    {% if post.venue%}<p class="archive__item-excerpt" itemprop="description">{{post.type}} at {{ post.venue }},  {{post.location}}</p>{% endif %}
_includes/archive-single-talk.html:    {% if post.venue %}<p class="archive__item-excerpt" itemprop="description">{{post.type}}, {{ post.venue }},  {{post.location}} {% endif %}
_includes/archive-single-talk.html:    {% if post.excerpt %}<p class="archive__item-excerpt" itemprop="description">{{ post.excerpt | markdownify }}</p>{% endif %}
_includes/archive-single.html:    {% if post.excerpt and site.read_more != 'enabled' %}
_includes/archive-single.html:    <p class="archive__item-excerpt" itemprop="description">{{ post.excerpt | markdownify }}</p>
_includes/archive-single.html:    {% elsif post.excerpt and site.read_more == 'enabled' %}
_includes/archive-single.html:    <p class="archive__item-excerpt" itemprop="description"><p>{{ post.excerpt | markdownify | remove: '<p>' | remove: '</p>' }}<strong><a href="{{ base_path }}{{ post.url }}" rel="permalink"> Read more</a></strong></p></p>

Not sure how to fix this run error by searching only over _pages/*.md?

**Comment by rjzupkoii** [comment] 2024-02-14 13:28
@alirk I didn't remove anything in the `_config.yml` file, but rather the `exerpt` line from the *.md files themselves. [This commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce) in my fork of academic pages is an example of the edit and you may need to make the change to multiple pages.

**Comment by alirk** [comment] 2024-02-14 13:36
> @alirk I didn't remove anything in the `_config.yml` file, but rather the `exerpt` line from the *.md files themselves. [This commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce) in my fork of academic pages is an example of the edit and you may need to make the change to multiple pages.

Thanks! It worked for me too. I had to remove lines including 'excerpt' in two files: 404.md and about.md both in _pages/ now it works :)

**Comment by mmdt01** [comment] 2024-02-14 14:37
Has the webpage theme/layout also changed for everyone else? I assume changes may being made atm...?

**Comment by gerardjoreilly** [comment] 2024-02-14 14:43
> > @alirk I didn't remove anything in the `_config.yml` file, but rather the `exerpt` line from the *.md files themselves. [This commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce) in my fork of academic pages is an example of the edit and you may need to make the change to multiple pages.
> 
> Thanks! It worked for me too. I had to remove lines including 'excerpt' in two files: 404.md and about.md both in _pages/ now it works :)

Thanks! I did this also and it builds without any issues now.

**Comment by JieRen98** [comment] 2024-02-14 15:48
> @alirk I didn't remove anything in the `_config.yml` file, but rather the `exerpt` line from the *.md files themselves. [This commit](https://github.com/rjzupkoii/rjzupkoii.github.io/commit/34d6d7766d5d40bfb2d2514a5124331daecd61ce) in my fork of academic pages is an example of the edit and you may need to make the change to multiple pages.

It does not work for me...

**Comment by ZiqiGuo98** [comment] 2024-02-14 21:46
Having the same issue... But I am using "excerpt" everywhere in the *.md file and it can be hard to remove all of them...

**Comment by BUAAZFK** [comment] 2024-02-15 06:19
I can not deploy the page now, errors occured in the step of 'deploy' which is 'Deploy to GitHub Pages'. Is this a problem of Github server? because I did not change anything, the first two tries succeed, and then never.

**Comment by griffinjmbur** [comment] 2024-02-16 21:53
Hi, all. I have happened upon this as a very new user. Funny thing is that I can't even find a line with "excerpt" in it, possibly because I cloned the repo after this post was written -->

> > Having the same issue... But I am using "excerpt" everywhere in the *.md file and it can be hard to remove all of them...
> 
> @ZiqiGuo98 I'm keeping an eye on the bug report in [jekyll/jekyll#9544](https://github.com/jekyll/jekyll/issues/9544), but it appears that a change to how the pages are built and deployed will be need for a robust fix. In the meantime, I'm removing the `excerpt` tag so that people can get back up and running.

... but I am having the same issue (the error message is that "The github-pages gem can't satisfy your Gemfile's dependencies.") My blog actually will publish, but the formatting is very strange. The local preview created with serve looks just fine, though.

**Comment by rjzupkoii** [comment] 2024-02-16 22:19
@griffinjmbur If you cloned after this issue was created then you should have that fix in place - I'm actually going to be closing this issue soon - however, the second problem sounds like it might be new and worth opening a new issue about. I'd need to see what the output you are getting looks like since this repository is deploying fine over github-pages.

**Comment by griffinjmbur** [comment] 2024-02-16 22:24
OK, thanks @rjzupkoii. I will try to write a very precise post since I am not a deft programmer outside minimal stuff in html or Stata/Python for stats. I could be missing something obvious, although I've troubleshot a lot of this process before successfully. Will post soon.

**Comment by rjzupkoii** [comment] 2024-02-24 15:51
Since it's been over a week now and I haven't seen any commenting on the issue still being a problem, I'm going to go ahead and close this issue.

**Closed by rjzupkoii** 2024-02-24 15:51 UTC
Labels: bug

**Comment by griffinjmbur** [comment] 2024-02-24 16:22
@rjzupkoii yep, this fully fixed the issue for me, per my comment in the other thread. Thanks a million dude!!
