### ISSUE TITLE
images not showing in sidebar

### ISSUE THREAD

**Issue by udion** [academicpages/academicpages.github.io#91] opened 2018-04-08 05:34 UTC
I have placed my profile picture in images folder and updated config.yml so that avatar has my image name, I am still not able to see my images, however if I put the names of the file which were there by default (i.e profile.png, etc..) it seems to work.

Please help

**Comment by TsingQAQ** [comment] 2018-05-11 10:01
Hi udion, I’ve encountered the same problem with yours. I could change the default profile images to other photos(png formatt only, jpg test failed) already included in the image file. However, when I uploaded a png photo, it didn't work. What's more, I can't make it work by renaming the uploaded photo to default: profile.png.
Have you solved this problem?

**Comment by udion** [comment] 2018-05-11 10:07
No, still no luck, I could find pages which are using the same template with their own images but could not find how they are doing it.
Please post the solution here if you do find out. (earlier I thought it has to do with the resolution of the images, but I tried the exact resolution as that of default profile.png, it doesn't work!)

**Comment by udion** [comment] 2018-05-12 16:10
check out HUGO!

**Comment by leonardopacciani** [comment] 2018-05-21 20:43
I have a similar problem: some images do work and show in the site (in my case I have added a photo in the "about" pages and it shows correctly) but some others don't, like the profile picture in the sidebar or any other image I add in any other page.
Is there any way to solve this without using HUGO?

**Comment by kruegert** [comment] 2018-06-01 22:38
I have the same problem. Is there any solution?

**Comment by bernielima** [comment] 2018-06-04 23:12
Well, I had the same problem, but no more.

Before i was puting in this way >>> avatar: "/images/be.png"
Working in this way>>>  avatar: "be.png"

**Comment by bernielima** [comment] 2018-06-04 23:45
Some toughts about the "config.yml" :

Correct >>>> avatar: name_of_the_picture.png 
Wrong >>>> avatar: /folder/name_of_the_picture.png

I tried 2 pictures. I worked out well, the other dont. (dont know why).

**Comment by lynchrobo** [comment] 2019-04-10 18:31
I've found that sometimes you need to capitalize the file type, i.e.

`my_photo.jpg`  doesn't work
`my_photo.JPG`  does work

I've had some issues with the photo showing up fine on the front page but not on subpages, but this seems to help at least partially.

**Comment by jiachangliu** [comment] 2019-09-15 20:25
I think one of the key issues is once you change the name after "avatar", you need to locally update it using git and upload it online to github using git as well. Once your images are uploaded on github, you should be able to display it locally using "bundle exec jekyll liveserve" as well.

The reason for this is that the generated index.html file under the _site folder has the location of the image points to your online github repository. Without uploading the images to github first, your local index.html will not display the image.

**Comment by ASeatonSpatial** [comment] 2019-09-24 13:04
I should mention my workflow is:

clone the forked repo
change things locally
commit changes
push to remote

Then I wait a bit and have a look at the website to see if I broke anything.  I've not tried displaying locally.

**Comment by ASeatonSpatial** [comment] 2019-09-24 13:18
Alright, a little bit strange, not sure if useful to anyone: I tried it locally using `bundle exec jekyll liveserve` and it worked.  After that I committed and pushed changes to remote and now it's working through github pages as well.

**Comment by yyou1996** [comment] 2020-05-02 20:03
> Did you change the base url in the config.yml file to your url?
> url  : https://[yourAccountName].github.io
> ...the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
> Otherwise the image is searched under https://academicpages.github.io

This works for me.

**Comment by Superhzf** [comment] 2020-09-08 09:28
> Did you change the base url in the config.yml file to your url?
> 
> url : https://[yourAccountName].github.io
> ...the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
> 
> Otherwise the image is searched under https://academicpages.github.io

To me, this basically works. Plus:
The format of the target image has to be original `.png`

**Comment by jkeller52** [comment] 2020-11-11 04:00
>Correct >>>> avatar: name_of_the_picture.png
>Wrong >>>> avatar: /folder/name_of_the_picture.png

For me, this wasn't the case. Changing my _config.yml to include /folder/filename.png solved the issue.

**Comment by zachwildd** [comment] 2021-01-26 05:15
Mine wasn't working with a. jpg, I converted my profile picture to a .png and now its working

**Comment by jroeder-astro** [comment] 2021-06-26 14:16
I know this thread has been dormant for a while, but none of the above solutions brought me any closer to my picture showing up on the page.

**Comment by kabbas570** [comment] 2021-07-28 08:04
> Did you change the base url in the config.yml file to your url?
> 
> url : https://[yourAccountName].github.io
> ...the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
> 
> Otherwise the image is searched under https://academicpages.github.io

Thanks, this one is working fine, change the URL and GitHub repo path.

**Comment by hbshrestha** [comment] 2022-06-09 23:38
I also faced this issue. I followed the following steps to resolve them:
- I used file of small size (<200 KB) for avatar.

In `config.yml` file,
- For the `avatar`, I simply used: "filename.JPG". I did not use "/images/filename.JPG". Note that I used JPG in capital.
- For `url`, I used `https://username.github.io` without quotes, where `username` refers to my personal user name
- For `baseurl`, I left it as just empty quotes `""`.
- For `repository`, I used name of the repository in my GitHub inside quotes "username.github.io" where `username` is my personal user name.

I committed these changes and pushe them into the repository.
Then I ran `bundle exec jekyll liveserve`. Finally I was able to see the image in the website after several attempts.

**Comment by JiyangZhang** [comment] 2022-10-16 21:05
> I've got this problem, i've changed the url and put my file in the images folder. I can see it in the repo on github, but when it searches [myrepo].github.io/images/myimage.jpg it doesn't find anything.
> 
> I've checked another repo and they have done exactly the same. When I check [hisrepo].github.io/images/hisimage.jpg the file is there. All he did was add it to the images folder same as me, why is my image not appearing?

super useful !

**Comment by davideboido** [comment] 2023-10-27 10:07
I found that my uploaded images were way too heavy and high-resolution than the original profile.png, that is 720x720 px @72 dpi. Once I resized my picture and commited it, it displayed correctly.
Hope it helps

**Comment by mx5nabcd** [comment] 2024-01-23 15:07
Delete everything behind the colon related to #Site Author(author) from the _config.yml file and commit. And if it's confirmed that it's all been deleted from your homepage, you can just add the photo again.

**Comment by rjzupkoii** [comment] 2024-02-17 21:23
Reading through the discussion there doesn't seem to be a bug in the underlying code, but we should add to the wiki a good write-up on how images are processed in the template.

**Comment by AlexandreGastonBellegarde** [comment] 2024-03-02 12:06
Ho i can run bundle exec jekyll liveserve ?

**Closed** 2024-08-17 15:24 UTC
Labels: documentation

**Comment by rlucas7** [comment] 2024-10-21 20:48
What I was able to do to fix this issue:

https://github.com/rlucas7/rlucas7.github.io/commit/e14176c45673bfe23fb160f06e26dc44ba78b926

basically I use the filepath base directory templating:
`"{{site.baseurl}}/<path-to-image-from-repo-root>.png"`
and place this in either `~[image]()` or the `<img src="filepath" />`. To be specific you replace

`~[image](filepage)`  ->  `~[image]({{site.baseurl}}/<path-to-image-from-repo-root>.png)`

or if you use html tags directly 

`<img src="{{site.baseurl}}/<path-to-image-from-repo-root>.png"/>`

there are a couple examples of both approaches in the commit referenced above in case you want something super concrete. 

Hope this helps.

**Comment by csaben** [comment] 2025-02-09 02:23
personally, when I had this issue it was due to a typo in the 
[author-profile.html](https://github.com/academicpages/academicpages.github.io/blob/master/_includes/author-profile.html) file.

line 13
```html
<img src="{{ author.avatar | prepend: "/images/" | prepend: base_path }}" class="author__avatar" alt="{{ author.name }}">
```

i initially had `" /images/"` (with an extra space) which will be decoded as %20 in your url to your image.

This can happen if you saved this file with `edit on save` in vscode.
