### ISSUE TITLE
Font awesome showing random symbols locally

### ISSUE THREAD

**Issue by alanjeffares** [academicpages/academicpages.github.io#852] opened 2022-02-02 11:41 UTC
When I download this repo everything seems to work as expected except the font-awesome icons in the sidebar seem to take on random images. When I run locally using `bundle exec jekyll serve` I obtain:

![](https://i.stack.imgur.com/pwsfOt.png)

But when I deploy that same code online, the icons render as expected:

![](https://i.stack.imgur.com/vz9Fyt.png)

Why would this be the case when I haven't changed the code at all? Note the solution in [this stackoverflow question](https://stackoverflow.com/questions/70944962/font-awesome-showing-random-symbols-locally) does not appear to solve the issue.

**Comment by rjzupkoii** [comment] 2024-02-14 17:16
Duplicate of #413

**Closed by rjzupkoii** 2024-02-14 17:16 UTC
Labels: duplicate
