### ISSUE TITLE
When setting future: false, posts with today's date aren't posted

### ISSUE THREAD

**Issue by MichaelMMeskhi** [academicpages/academicpages.github.io#53] opened 2017-11-10 07:46 UTC
I create a new post like this: 

---
title: 'Domain Adaptation'
date: **2012**-11-10
permalink: /posts/domain-adaptation/
tags:
  - machine learning
  - domain adaptation
---

It creates a posts folder in _site and works but when I change the dates to:

---
title: 'Domain Adaptation'
date: **2017**-11-10
permalink: /posts/domain-adaptation/
tags:
  - machine learning
  - domain adaptation
---

The posts folder disappears and posts dont show up on the website.

**Comment by MichaelMMeskhi** [comment] 2017-11-10 07:55
Had date issues. Apparently using today's date, 2017-11-10 was not generating the post but using 2017-11-09 worked. Huh go figure...

**Comment by naoto0804** [comment] 2018-07-27 07:12
I've been stacked exactly the same problem. Thank you so much for providing solution.

**Comment by staeiou** [comment] 2018-07-27 16:22
Hi, this is supposed to be a feature so that future posts can be written ahead of time and scheduled, but seems it isn't working for today's date. You can edit `_config.yml` to add `future: true` to show future posts. The default is false -- I've now made `future: true` the default in the main repo.

**Comment by rjzupkoii** [comment] 2024-02-17 21:20
Tried to reproduce locally using today's date and was unable to. This might have been corrected by an update in the underlying libraries or could be an edge case (i.e., server time vs. local time) that would require more information. Closing due to the age of the issue and inability to reproduce.

**Closed by rjzupkoii** 2024-02-17 21:20 UTC
Labels: bug, cannot reproduce
