### ISSUE TITLE
table of contents do no look well

### ISSUE THREAD

**Issue by junqing-zhang** [academicpages/academicpages.github.io#221] opened 2019-04-16 21:39 UTC
I was trying to use table of contents for the posts and pages. It worked but the format did not look well. I wonder if anyone had similar issue.

**Comment by ningyuansg** [comment] 2019-04-16 22:56
Can you include a screenshot? There are many different ways that the table of contents can 'not look well'.

**Comment by junqing-zhang** [comment] 2019-04-17 07:29
Hello ningyuansg, please see the two screenshot below.
![toc_page](https://user-images.githubusercontent.com/25430928/56269032-a813e280-60ea-11e9-8416-1a3e9b6acf94.png)
![toc_post](https://user-images.githubusercontent.com/25430928/56269033-a8ac7900-60ea-11e9-8151-689e9ef78ff2.png)

I have also enabled the toc in my links now and you can visit them 
https://junqing-zhang.github.io/publication/
https://junqing-zhang.github.io/posts/2019/04/12/keygendemo/

Many thanks for the help.

**Comment by junqing-zhang** [comment] 2019-04-17 08:49
I checked on the mobile side and it looked well, as the screenshot shown below:
![toc_mobile](https://user-images.githubusercontent.com/25430928/56274074-f5498180-60f5-11e9-8c05-3e8af8374575.jpg)

**Comment by bertolinocastro** [comment] 2020-07-19 22:16
Hi! I just came up with this same issue and saw that my problem was some "width: 0px" style at the `_sass/sidebar` style sheet. I just commented both occurences and voilà.

**Comment by lzkelley** [comment] 2023-11-20 18:37
The above fix didn't exactly work for me, but the same idea, [these lines in `_sass/_variables.scss`](https://github.com/academicpages/academicpages.github.io/blob/master/_sass/_variables.scss#L123-L125) were set to zero widths:

```
$right-sidebar-width-narrow : 0px;
$right-sidebar-width        : 0px;
$right-sidebar-width-wide   : 0px
```

I change each of them to `float` and this fixed the problem.

**Comment by rjzupkoii** [comment] 2024-02-14 19:16
This might be addressed between updating the libraries and doing the basic refresh.

**Comment by rjzupkoii** [comment] 2024-04-14 14:42
I'm unable to reproduce this behavior using the Chrome Web Developer tools, so this might have gotten fixed with the other revisions. I'm going to go ahead and close this issue for now.

**Closed by rjzupkoii** 2024-04-14 14:42 UTC
Labels: bug

**Comment by qhuang-math** [comment] 2024-07-11 08:59
The problem addressed by @bertolinocastro also happened to me, while the solution by @lzkelley didn't work for me. I tried the following variables found in [jayrobwilliams.github.io/_sass](https://github.com/jayrobwilliams/jayrobwilliams.github.io/tree/master/_sass)/_variables.scss
```
$right-sidebar-width-narrow : 200px !default;
$right-sidebar-width        : 300px !default;
$right-sidebar-width-wide   : 400px !default;
```
they worked well.

**Comment by nathanpainchaud** [comment] 2025-05-04 13:01
@rjzupkoii This doesn't seem fixed to me... I get the following ToC with the most recent git version of the repo (commit ef8e08b653e57d26e6f0e3086edcd12df077c431), which includes the supposed fix proposed by @qhuang-math.

![Image](https://github.com/user-attachments/assets/606bcc1b-970b-4d44-89e1-4a0bf1be39f3)

**Comment by rjzupkoii** [comment] 2025-05-04 13:50
@nathanpainchaud What browser, device, and operating system are you on?

**Comment by nathanpainchaud** [comment] 2025-05-04 14:32
> [@nathanpainchaud](https://github.com/nathanpainchaud) What browser, screen resolution, device, and operating system are you on?

@rjzupkoii Thanks for the quick follow up! The info you asked for:

- Tested on 3 different browsers (all up-to-date), all give the same appearance:
  - Chrome: Version 136.0.7103.59 (Official Build) (64-bit)
  - Firefox: 138.0.1 (64-bit)
  - Vivaldi: 7.3.3635.11 (Stable channel) stable (64-bit) 
- Operating System: Linux EndeavourOS (arch-based), kernel version 6.14.4-arch1-2
- Device & Display:
```console
↪ inxi -G
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Barcelo driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.16 with: Xwayland v: 24.1.6 driver: X:
    loaded: amdgpu unloaded: modesetting dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 25.0.4-arch1.1
    renderer: AMD Radeon Graphics (radeonsi renoir ACO DRM 3.61 6.14.4-arch1-2)
  Info: Tools: api: eglinfo,glxinfo x11: xdpyinfo, xprop, xrandr
```

**Comment by rjzupkoii** [comment] 2025-05-04 19:07
@nathanpainchaud Nothing really stands out there as a possible cause and a couple of those are what I also use for testing the template (i.e., https://academicpages.github.io/). That likely means it's a chance you made for your site, can you create a new ticket with a link to your repository as well so that I can take a look at the code?

**Comment by nathanpainchaud** [comment] 2025-05-05 08:48
> can you create a new ticket with a link to your repository as well so that I can take a look at the code?

Thanks again for the follow-up! I've opened a new issue like you asked here #3019.
