### ISSUE TITLE
Remove space below header in 'About' tab

### ISSUE THREAD

**Issue by guilimberg** [academicpages/academicpages.github.io#1473] opened 2023-08-01 18:19 UTC
Has anyone been able to shorten the space between the 'about' (main) tab and the header? 

All other tabs have way less space below the header and the page title. 

Thanks!

**Comment by rjzupkoii** [comment] 2024-02-20 22:26
Which browser did you see this in? I'm not sure I'm seeing the extra space you are referring in the stock template.

**Comment by rjzupkoii** [comment] 2024-03-10 18:43
Since there has been no follow-up and I can't seem to find the source of the problem, closing as unreproducible.

**Closed by rjzupkoii** 2024-03-10 18:43 UTC
Labels: cannot reproduce
