### ISSUE TITLE
Add collection

### ISSUE THREAD

**Issue by SourojitGhosh** [academicpages/academicpages.github.io#1721] opened 2023-11-17 17:16 UTC
I'm trying to add a new collection exactly like "Talks" to my page, called "Work". What steps do I need to take, what files to create, and what additions to make to existing files?

I have created a folder called _work and made files like work-1.md in it. I have also updated the _navigation with the new tab. I have added a work.html file in pages that looks exactly like talks.html. But I still cannot get the content working.

**Comment by rjzupkoii** [comment] 2024-02-14 16:15
Appears to be duplicate of #1655

**Closed by rjzupkoii** 2024-02-14 16:15 UTC
Labels: question
